[package]
name = "warframe-market-widget"
version = "1.2.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
autotests = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
overcrow-widget-sdk = { path = "../../sdk/rust/overcrow-widget-sdk", default-features = false, features = ["api-v2"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
