#!/bin/sh
set -eu

if test "$#" -ne 0; then
    printf '%s\n' 'usage: sandbox-component-build-smoke.sh' >&2
    exit 2
fi

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)
helper="$repo_root/scripts/sandbox-component-build.sh"
scratch=$(/usr/bin/mktemp -d /tmp/marketplace-sandbox.XXXXXXXXXX)
listener_pid=''
cleanup() {
    if test -n "$listener_pid"; then
        /usr/bin/kill "$listener_pid" 2>/dev/null || true
        wait "$listener_pid" 2>/dev/null || true
    fi
    /usr/bin/rm -rf -- "$scratch"
}
trap cleanup EXIT HUP INT TERM

canary="$scratch/private-canary"
private_argument="$scratch/production-signing-state"
parent_home=$(CDPATH='' cd -- && pwd -P)
printf '%s\n' 'OVERCR0W-SANDBOX-CANARY' >"$canary"
/usr/bin/chmod 0600 "$canary"
printf '%s\n' 'publisher state must stay private' >"$private_argument"
/usr/bin/chmod 0600 "$private_argument"

listener="$scratch/listener.py"
port_file="$scratch/listener-port"
printf '%s\n' \
    'import pathlib, socket, sys' \
    'server = socket.socket()' \
    'server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)' \
    'server.bind(("127.0.0.1", 0))' \
    'server.listen(1)' \
    'pathlib.Path(sys.argv[1]).write_text(str(server.getsockname()[1]), encoding="ascii")' \
    'server.settimeout(30)' \
    'try:' \
    '    connection, _ = server.accept()' \
    '    connection.close()' \
    'except TimeoutError:' \
    '    pass' >"$listener"
python3 "$listener" "$port_file" "$private_argument" &
listener_pid=$!
attempt=0
while test ! -s "$port_file"; do
    attempt=$((attempt + 1))
    if test "$attempt" -ge 100; then
        printf '%s\n' 'error: loopback canary did not start' >&2
        exit 1
    fi
    /usr/bin/sleep 0.05
done
port=$(/usr/bin/cat "$port_file")

sandbox_root="$scratch/build-roots"
source_root="$sandbox_root/source"
target_root="$sandbox_root/output"
/usr/bin/install -d -m 0700 "$source_root/src" "$target_root"
printf '%s\n' \
    '[package]' \
    'name = "sandbox-canary"' \
    'version = "0.1.0"' \
    'edition = "2024"' \
    'build = "build.rs"' \
    '' \
    '[lib]' \
    'crate-type = ["cdylib"]' >"$source_root/Cargo.toml"
printf '%s\n' \
    '# This file is automatically @generated by Cargo.' \
    '# It is not intended for manual editing.' \
    'version = 4' \
    '' \
    '[[package]]' \
    'name = "sandbox-canary"' \
    'version = "0.1.0"' >"$source_root/Cargo.lock"
printf '%s\n' '#[unsafe(no_mangle)] pub extern "C" fn canary() {}' >"$source_root/src/lib.rs"
printf '%s\n' \
    'use std::{env, fs, net::TcpStream};' \
    'fn main() {' \
    "    if fs::read(\"$canary\").is_ok() { let _ = fs::write(\"/output/canary-leak\", b\"seen\"); }" \
    "    if TcpStream::connect((\"127.0.0.1\", $port)).is_ok() { let _ = fs::write(\"/output/network-leak\", b\"seen\"); }" \
    "    if env::vars_os().any(|(key, value)| key == \"OVERCROW_PRIVATE_ARGUMENT\" || value == \"$private_argument\") { let _ = fs::write(\"/output/environment-leak\", b\"seen\"); }" \
    "    if env::var_os(\"HOME\").as_deref() != Some(std::ffi::OsStr::new(\"/home/build\")) { let _ = fs::write(\"/output/home-leak\", b\"seen\"); }" \
    "    if fs::read_dir(\"$parent_home\").is_ok() { let _ = fs::write(\"/output/host-home-leak\", b\"seen\"); }" \
    '    if let Ok(entries) = fs::read_dir("/proc") {' \
    '        for entry in entries.flatten() {' \
    '            let path = entry.path().join("cmdline");' \
    "            if fs::read(path).is_ok_and(|bytes| bytes.windows(${#private_argument}).any(|window| window == \"$private_argument\".as_bytes())) { let _ = fs::write(\"/output/process-leak\", b\"seen\"); }" \
    '        }' \
    '    }' \
    '}' >"$source_root/build.rs"

/usr/bin/cp -a -- "$source_root" "$scratch/source-before"
OVERCROW_PRIVATE_ARGUMENT="$private_argument" sh "$helper" "$source_root" "$target_root"
/usr/bin/diff --recursive --no-dereference "$scratch/source-before" "$source_root"
test -f "$target_root/target/wasm32-wasip2/release/sandbox_canary.wasm"
for leak in canary-leak network-leak environment-leak home-leak host-home-leak process-leak; do
    test ! -e "$target_root/$leak" && test ! -L "$target_root/$leak"
done
test "$(/usr/bin/find "$sandbox_root" -mindepth 1 -maxdepth 1 -printf '%f\n' | /usr/bin/sort)" = "output
source"

include_source="$scratch/include-source"
include_target="$scratch/include-output"
/usr/bin/install -d -m 0700 "$include_source/src" "$include_target"
printf '%s\n' \
    '[package]' \
    'name = "include-canary"' \
    'version = "0.1.0"' \
    'edition = "2024"' \
    '' \
    '[lib]' \
    'crate-type = ["cdylib"]' >"$include_source/Cargo.toml"
printf '%s\n' \
    '# This file is automatically @generated by Cargo.' \
    '# It is not intended for manual editing.' \
    'version = 4' \
    '' \
    '[[package]]' \
    'name = "include-canary"' \
    'version = "0.1.0"' >"$include_source/Cargo.lock"
printf 'pub static CANARY: &[u8] = include_bytes!("%s");\n' "$canary" >"$include_source/src/lib.rs"
if sh "$helper" "$include_source" "$include_target"; then
    printf '%s\n' 'error: include_bytes observed an external canary' >&2
    exit 1
fi
test ! -e "$include_target/include-leak" && test ! -L "$include_target/include-leak"

missing_target="$scratch/missing-bwrap-output"
/usr/bin/install -d -m 0700 "$missing_target"
if env PATH=/no-trusted-tools /bin/sh "$helper" "$source_root" "$missing_target"; then
    printf '%s\n' 'error: sandbox build succeeded without Bubblewrap' >&2
    exit 1
fi
test -z "$(/usr/bin/find "$missing_target" -mindepth 1 -print -quit)"

printf '%s\n' 'Component sandbox smoke tests passed'
