#!/bin/sh
set -eu
umask 077

if test "$#" -ne 0; then
    printf '%s\n' 'usage: sandbox-review-checks-smoke.sh' >&2
    exit 2
fi

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)
helper="$repo_root/scripts/sandbox-review-checks.sh"
if test ! -x "$helper" || test -L "$helper"; then
    printf '%s\n' 'error: review-check sandbox is missing or unsafe' >&2
    exit 1
fi

scratch=$(/usr/bin/mktemp -d /tmp/marketplace-review-sandbox.XXXXXXXXXX)
listener_pid=''
cleanup() {
    if test -n "$listener_pid"; then
        /usr/bin/kill "$listener_pid" 2>/dev/null || true
        wait "$listener_pid" 2>/dev/null || true
    fi
    /usr/bin/rm -rf -- "$scratch"
}
trap cleanup EXIT HUP INT TERM

host_canary="$scratch/host-canary"
printf '%s\n' 'must remain unchanged' >"$host_canary"
process_secret="marketplace-host-process-$$_canary"
listener="$scratch/listener.py"
port_file="$scratch/listener-port"
printf '%s\n' \
    'import pathlib, socket, sys' \
    'server = socket.socket()' \
    'server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)' \
    'server.bind(("127.0.0.1", 0))' \
    'server.listen(1)' \
    'pathlib.Path(sys.argv[1]).write_text(str(server.getsockname()[1]), encoding="ascii")' \
    'server.settimeout(30)' \
    'try:' \
    '    connection, _ = server.accept()' \
    '    connection.close()' \
    'except TimeoutError:' \
    '    pass' >"$listener"
python3 "$listener" "$port_file" "$process_secret" &
listener_pid=$!
attempt=0
while test ! -s "$port_file"; do
    attempt=$((attempt + 1))
    if test "$attempt" -ge 100; then
        printf '%s\n' 'error: review sandbox loopback canary did not start' >&2
        exit 1
    fi
    /usr/bin/sleep 0.05
done
port=$(/usr/bin/cat "$port_file")

fixture="$scratch/workspace"
/usr/bin/install -d -m 0700 -- "$fixture/canary/src"
printf '%s\n' \
    '[workspace]' \
    'members = ["canary"]' \
    'resolver = "3"' >"$fixture/Cargo.toml"
printf '%s\n' \
    '# This file is automatically @generated by Cargo.' \
    '# It is not intended for manual editing.' \
    'version = 4' \
    '' \
    '[[package]]' \
    'name = "review-sandbox-canary"' \
    'version = "0.1.0"' >"$fixture/Cargo.lock"
printf '%s\n' \
    '[toolchain]' \
    'channel = "1.98.0"' \
    'profile = "minimal"' >"$fixture/rust-toolchain.toml"
printf '%s\n' \
    '[package]' \
    'name = "review-sandbox-canary"' \
    'version = "0.1.0"' \
    'edition = "2024"' >"$fixture/canary/Cargo.toml"
printf '%s\n' \
    '#[cfg(test)]' \
    'mod tests {' \
    '    use std::{fs, net::TcpStream};' \
    '' \
    '    #[test]' \
    '    fn ordinary_test_still_runs() {' \
    '        assert_eq!(2 + 2, 4);' \
    '    }' \
    '' \
    '    #[test]' \
    '    fn host_boundaries_are_closed() {' \
    '        assert!(' \
    '            fs::write(' \
    "                \"$host_canary\"," \
    '                b"changed"' \
    '            )' \
    '            .is_err()' \
    '        );' \
    "        assert!(TcpStream::connect((\"127.0.0.1\", $port)).is_err());" \
    '        let status = fs::read_to_string("/proc/self/status").expect("process status");' \
    '        for capability in ["CapInh", "CapPrm", "CapEff", "CapBnd", "CapAmb"] {' \
    '            assert!(status.contains(&format!("{capability}:\t0000000000000000")));' \
    '        }' \
    '        assert!(status.contains("NoNewPrivs:\t1"));' \
    '        assert!(fs::write("/source/canary/source-mutation", b"changed").is_err());' \
    '        let host_process_is_visible = fs::read_dir("/proc")' \
    '            .into_iter()' \
    '            .flatten()' \
    '            .flatten()' \
    '            .filter_map(|entry| fs::read(entry.path().join("cmdline")).ok())' \
    '            .any(|bytes| {' \
    '                bytes' \
    "                    .windows(${#process_secret})" \
    "                    .any(|window| window == b\"$process_secret\")" \
    '            });' \
    '        assert!(!host_process_is_visible);' \
    '    }' \
    '}' >"$fixture/canary/src/lib.rs"

/usr/bin/cp -a -- "$fixture" "$scratch/workspace-before"
sh "$helper" workspace "$fixture"
/usr/bin/diff --recursive --no-dereference \
    "$scratch/workspace-before" "$fixture"
test "$(/usr/bin/cat "$host_canary")" = 'must remain unchanged'
test ! -e "$fixture/canary/source-mutation" \
    && test ! -L "$fixture/canary/source-mutation"

/usr/bin/install -d -m 0700 -- "$fixture/skipped/src"
/usr/bin/sed -i 's/members = \["canary"\]/members = ["canary", "skipped"]/' \
    "$fixture/Cargo.toml"
printf '%s\n' \
    '' \
    '[[package]]' \
    'name = "review-sandbox-skipped"' \
    'version = "0.1.0"' >>"$fixture/Cargo.lock"
printf '%s\n' \
    '[package]' \
    'name = "review-sandbox-skipped"' \
    'version = "0.1.0"' \
    'edition = "2024"' >"$fixture/skipped/Cargo.toml"
printf '%s\n' \
    '#[test]' \
    'fn must_not_run() {' \
    '    panic!("unchanged package was retested");' \
    '}' >"$fixture/skipped/src/lib.rs"
review_plan="$scratch/review-plan.tsv"
printf 'review-sandbox-canary\tcanary\tcanary\n' >"$review_plan"
/usr/bin/chmod 0600 "$review_plan"
sh "$helper" workspace "$fixture" "$fixture" "$review_plan"

# Prove that the plan is consumed, not merely accepted: selecting the known
# failing package must fail, while the preceding canary-only plan passed.
printf 'review-sandbox-skipped\tskipped\tskipped\n' >"$review_plan"
if sh "$helper" workspace "$fixture" "$fixture" "$review_plan" \
        >"$scratch/selected-failure.stdout" \
        2>"$scratch/selected-failure.stderr"; then
    printf '%s\n' 'error: selected package tests were not executed' >&2
    exit 1
fi

printf '%s\n' 'Review-check sandbox smoke tests passed'
