"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const test = require("node:test");
const vm = require("node:vm");

class Element { constructor(tag = "div") { this.tagName = tag; this.children = []; this.listeners = new Map(); this.textContent = ""; this.value = "en"; } append(...items) { this.children.push(...items); } replaceChildren(...items) { this.children = items; } addEventListener(type, listener) { this.listeners.set(type, listener); } dispatch(type) { this.listeners.get(type)(); } }
const catalogPath = "public/marketplace/v1/catalog.json";
function generated() { return fs.readFileSync(catalogPath, "utf8"); }
function payload(body) { const envelope = JSON.parse(body); return JSON.parse(Buffer.from(envelope.payload, "base64url")); }
function withTargets(change) { const envelope = JSON.parse(generated()); const body = JSON.parse(Buffer.from(envelope.payload, "base64url")); envelope.payload = Buffer.from(JSON.stringify({ ...body, targets: change(body.targets) })).toString("base64url"); return JSON.stringify(envelope); }
function streamed(body) { let sent = false; return { getReader: () => ({ read: async () => sent ? { done: true } : (sent = true, { done: false, value: new Uint8Array(Buffer.from(body)) }) }) }; }
async function run(body, options = {}) { const catalog = new Element(); const language = new Element("select"); const document = { createElement: (tag) => new Element(tag), getElementById: (id) => id === "catalog" ? catalog : language, documentElement: { lang: "en" } }; const requests = []; const context = { document, TextDecoder, Uint8Array, atob: (value) => Buffer.from(value, "base64").toString("binary"), fetch: async (url) => { requests.push(url); return { ok: true, headers: { get: () => options.contentLength }, body: options.noBody ? undefined : streamed(body) }; } }; vm.runInNewContext(fs.readFileSync("site/app.js", "utf8"), context); await new Promise((resolve) => setImmediate(resolve)); await new Promise((resolve) => setImmediate(resolve)); return { catalog, language, document, requests }; }
function cardText(card) { return card.children.map((child) => child.textContent).join("\n"); }
function unavailable(page) { assert.equal(page.catalog.children.length, 1); assert.equal(page.catalog.children[0].textContent, "Catalog unavailable."); }

test("renders the actual generated signed catalog", async () => { const body = generated(); const actual = payload(body); assert.equal(actual.targets.length, 6); const page = await run(body); const index = fs.readFileSync("site/index.html", "utf8"); assert.match(index, /<option value="en" selected>English<\/option>/); assert.match(index, /<option value="fr">Français<\/option>/); assert.deepEqual(page.requests, ["/marketplace/v1/catalog.json"]); assert.equal(page.catalog.children.length, 5); const fissures = cardText(page.catalog.children.find((card) => /Warframe Void Fissures/.test(cardText(card)))); assert.match(fissures, /Includes dependency: Warframe Worldstate Provider/); assert.match(fissures, /Fetches public data from: api\.warframe\.com/); assert.match(fissures, /Reads OverCrow session data/); assert.match(fissures, /Stores private widget settings/); assert.match(fissures, /Publishes bounded public world-state data/); const market = cardText(page.catalog.children.find((card) => /Warframe Market/.test(cardText(card)))); for (const text of [/api\.warframe\.market/, /Reads OverCrow session data/, /Stores private widget settings/, /Writes a trade message to clipboard/]) assert.match(market, text); });

const firstConsumer = (targets) => targets.findIndex((target) => target.manifest.kind === "widget");
for (const [name, body, options] of [["lying length", "x".repeat(1024 * 1024 + 1), { contentLength: "1" }], ["missing length", "x".repeat(1024 * 1024 + 1), {}], ["absent stream", generated(), { noBody: true }], ["malformed envelope", "{}", {}], ["wrong dependency version", withTargets((targets) => { const index = firstConsumer(targets); targets[index].manifest.dependencies[0].version = "9.9.9"; return targets; }), {}], ["wrong dependency hash", withTargets((targets) => { const index = firstConsumer(targets); targets[index].manifest.dependencies[0].sha256 = "b".repeat(64); return targets; }), {}]]) test(`rejects ${name}`, async () => unavailable(await run(body, options)));
