"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const test = require("node:test");
const vm = require("node:vm");

class Element { constructor(tag = "div") { this.tagName = tag; this.children = []; this.listeners = new Map(); this.textContent = ""; this.value = "en"; } append(...items) { this.children.push(...items); } replaceChildren(...items) { this.children = items; } addEventListener(type, listener) { this.listeners.set(type, listener); } dispatch(type) { this.listeners.get(type)(); } }
const sha = "a".repeat(64);
function target(id, kind, status, dependencies, capabilities, en, fr) { return { manifest: { id, version: "1.0.0", kind, defaultLocale: "en", availableLocales: ["en", "fr"], games: ["warframe"], dependencies, capabilities }, listing: { author: "PlayerVox", spdxLicense: "MIT", sourceUrl: "https://example.invalid/source", localizations: [{ locale: "en", name: en, description: `${en} description` }, { locale: "fr", name: fr, description: `${fr} description` }] }, packageUrl: `packages/${id}-1.0.0.ocpkg`, packageSize: 1, packageSha256: sha, minHostApi: 1, maxHostApi: 1, status }; }
const provider = target("com.playervox.overcrow.warframe.worldstate", "provider", "verified", [], { http: ["api.warframe.com"], gameData: [], storage: false, clipboardWrite: false, provider: true }, "Warframe Worldstate Provider", "Fournisseur d’état mondial Warframe");
const dependency = { id: provider.manifest.id, version: provider.manifest.version, sha256: provider.packageSha256 };
const session = { http: [], gameData: ["overcrow.session.v1"], storage: true, clipboardWrite: false, provider: false };
const targets = [provider, target("status", "widget", "verified", [dependency], session, "Warframe Status", "Statut Warframe"), target("fissures", "widget", "verified", [dependency], session, "Warframe Void Fissures", "Fissures du Néant Warframe"), target("sortie", "widget", "verified", [dependency], session, "Warframe Sortie & Archon Hunt", "Sortie et Chasse à l’Archonte Warframe"), target("invasions", "widget", "verified", [dependency], session, "Warframe Invasions", "Invasions Warframe"), target("market", "bundle", "verified", [], { http: ["api.warframe.market"], gameData: ["overcrow.session.v1"], storage: true, clipboardWrite: true, provider: false }, "Warframe Market", "Marché Warframe")];
function envelope(records = targets) { const payload = Buffer.from(JSON.stringify({ schemaVersion: 1, sequence: 2, generatedAt: "2026-08-27T00:00:00Z", expiresAt: "2036-08-27T00:00:00Z", targets: records })).toString("base64url"); return JSON.stringify({ schemaVersion: 1, keyId: "overcrow-development-2026", payload, signature: "x".repeat(86) }); }
function streamed(body, chunks = [body]) { let index = 0; return { getReader: () => ({ read: async () => index < chunks.length ? { done: false, value: new Uint8Array(Buffer.from(chunks[index++])) } : { done: true } }) }; }
async function run(body, options = {}) { const catalog = new Element(); const language = new Element("select"); const document = { createElement: (tag) => new Element(tag), getElementById: (id) => id === "catalog" ? catalog : language, documentElement: { lang: "en" } }; const requests = []; const context = { document, TextDecoder, Uint8Array, atob: (value) => Buffer.from(value, "base64").toString("binary"), fetch: async (url) => { requests.push(url); return { ok: true, headers: { get: () => options.contentLength }, body: options.noBody ? undefined : streamed(body, options.chunks) }; } }; vm.runInNewContext(fs.readFileSync("site/app.js", "utf8"), context); await new Promise((resolve) => setImmediate(resolve)); await new Promise((resolve) => setImmediate(resolve)); return { catalog, language, document, requests }; }
function cardText(card) { return card.children.map((child) => child.textContent).join("\n"); }
function unavailable(page) { assert.equal(page.catalog.children.length, 1); assert.equal(page.catalog.children[0].textContent, "Catalog unavailable."); }

test("renders the fixed five-card catalog with exact labels, dependencies, and permissions", async () => { const page = await run(envelope(), { contentLength: undefined }); const index = fs.readFileSync("site/index.html", "utf8"); assert.match(index, /<option value="en" selected>English<\/option>/); assert.match(index, /<option value="fr">Français<\/option>/); assert.match(index, /Only OverCrow Control Center verifies signatures and installs packages\./); assert.deepEqual(page.requests, ["/marketplace/v1/catalog.json"]); assert.equal(page.catalog.children.length, 5); const status = cardText(page.catalog.children[0]); assert.match(status, /Includes dependency: Warframe Worldstate Provider/); assert.match(status, /Fetches public data from: api\.warframe\.com/); assert.match(status, /Reads OverCrow session data/); assert.match(status, /Stores private widget settings/); assert.match(status, /Publishes bounded public world-state data/); const market = cardText(page.catalog.children[4]); assert.match(market, /Fetches public data from: api\.warframe\.market/); assert.match(market, /Reads OverCrow session data/); assert.match(market, /Stores private widget settings/); assert.match(market, /Writes a trade message to clipboard/); page.language.value = "fr"; page.language.dispatch("change"); assert.equal(page.document.documentElement.lang, "fr"); assert.equal(page.catalog.children[0].children[0].textContent, "Statut Warframe"); });

for (const [name, body, options] of [["oversized stream with lying Content-Length", "x".repeat(1024 * 1024 + 1), { contentLength: "1" }], ["oversized stream without Content-Length", "x".repeat(1024 * 1024 + 1), {}], ["absent stream", envelope(), { noBody: true }], ["malformed envelope", "{}", {}], ["incomplete target", envelope([{ ...targets[1], packageSha256: undefined }]), {}], ["wrong dependency version", envelope([{ ...targets[1], manifest: { ...targets[1].manifest, dependencies: [{ ...dependency, version: "9.9.9" }] } }]), {}], ["wrong dependency hash", envelope([{ ...targets[1], manifest: { ...targets[1].manifest, dependencies: [{ ...dependency, sha256: "b".repeat(64) }] } }]), {}], ["suspended status", envelope([{ ...targets[1], status: "security-suspended" }]), {}], ["revoked status", envelope([{ ...targets[1], status: "revoked" }]), {}]]) test(`rejects ${name}`, async () => unavailable(await run(body, options)));
