"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const test = require("node:test");
const vm = require("node:vm");
class Element { constructor(tag = "div") { this.tagName = tag; this.children = []; this.listeners = new Map(); this.textContent = ""; this.value = "en"; } append(...items) { this.children.push(...items); } replaceChildren(...items) { this.children = items; } addEventListener(type, listener) { this.listeners.set(type, listener); } dispatch(type) { this.listeners.get(type)(); } }
function target(id, kind, status, dependencies, capabilities, en, fr) { return { manifest: { id, kind, defaultLocale: "en", availableLocales: ["en", "fr"], dependencies, capabilities }, listing: { localizations: [{ locale: "en", name: en, description: `${en} description` }, { locale: "fr", name: fr, description: `${fr} description` }] }, status }; }
const provider = target("com.playervox.overcrow.warframe.worldstate", "provider", "verified", [], { http: ["api.warframe.com"], gameData: [], storage: false, clipboardWrite: false, provider: true }, "Warframe Worldstate Provider", "Fournisseur d’état mondial Warframe");
const dependency = { id: provider.manifest.id, version: "1.0.0", sha256: "a".repeat(64) };
const session = { http: [], gameData: ["overcrow.session.v1"], storage: true, clipboardWrite: false, provider: false };
const targets = [provider, target("status", "widget", "verified", [dependency], session, "Warframe Status", "Statut Warframe"), target("fissures", "widget", "verified", [dependency], session, "Warframe Void Fissures", "Fissures du Néant Warframe"), target("sortie", "widget", "verified", [dependency], session, "Warframe Sortie & Archon Hunt", "Sortie et Chasse à l’Archonte Warframe"), target("invasions", "widget", "verified", [dependency], session, "Warframe Invasions", "Invasions Warframe"), target("market", "bundle", "verified", [], { http: ["api.warframe.market"], gameData: ["overcrow.session.v1"], storage: true, clipboardWrite: true, provider: false }, "Warframe Market", "Marché Warframe")];
function envelope(records = targets) { const payload = Buffer.from(JSON.stringify({ schemaVersion: 1, sequence: 2, generatedAt: "2026-08-27T00:00:00Z", expiresAt: "2036-08-27T00:00:00Z", targets: records })).toString("base64url"); return JSON.stringify({ schemaVersion: 1, keyId: "overcrow-development-2026", payload, signature: "x".repeat(86) }); }
async function run(body) { const catalog = new Element(); const language = new Element("select"); const document = { createElement: (tag) => new Element(tag), getElementById: (id) => id === "catalog" ? catalog : language, documentElement: { lang: "en" } }; const requests = []; const context = { document, TextDecoder, Uint8Array, atob: (value) => Buffer.from(value, "base64").toString("binary"), fetch: async (url) => { requests.push(url); return { ok: true, headers: { get: () => String(body.length) }, text: async () => body }; } }; vm.runInNewContext(fs.readFileSync("site/app.js", "utf8"), context); await new Promise((resolve) => setImmediate(resolve)); await new Promise((resolve) => setImmediate(resolve)); return { catalog, language, document, requests }; }
function cardText(card) { return card.children.map((child) => child.textContent).join("\n"); }
test("renders five cards, switches French, and discloses fixed permissions", async () => { const page = await run(envelope()); assert.deepEqual(page.requests, ["/marketplace/v1/catalog.json"]); assert.equal(page.catalog.children.length, 5); assert.equal(page.catalog.children[0].children[0].textContent, "Warframe Status"); assert.match(cardText(page.catalog.children[0]), /Fetches public data from: api.warframe.com/); assert.match(cardText(page.catalog.children[4]), /Writes a trade message to clipboard/); page.language.value = "fr"; page.language.dispatch("change"); assert.equal(page.document.documentElement.lang, "fr"); assert.equal(page.catalog.children[0].children[0].textContent, "Statut Warframe"); assert.match(cardText(page.catalog.children[4]), /Écrit un message d’échange dans le presse-papiers/); });
for (const [name, body] of [["oversized", "x".repeat(1024 * 1024 + 1)], ["malformed envelope", "{}"], ["malformed kind", envelope([{ ...targets[1], manifest: { ...targets[1].manifest, kind: "unknown" } }])], ["suspended status", envelope([{ ...targets[1], status: "security-suspended" }])], ["revoked status", envelope([{ ...targets[1], status: "revoked" }])]]) test(`rejects ${name}`, async () => { const page = await run(body); assert.equal(page.catalog.children.length, 1); assert.equal(page.catalog.children[0].textContent, "Catalog unavailable."); });
